sudo: required
language: java
jdk:
  - openjdk11
services:
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)
    - appversion=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

after_success:
  - bash <(curl -s https://codecov.io/bash)

script:
  - mvn clean install
  - docker build -t dhananjay12/demo-app:$appversion-travis .
  - docker push dhananjay12/demo-app:$appversion-travis