server:
  port: ${PORT:8080}
spring:
  docker:
    compose:
      enabled: true
      lifecycle-management: start_and_stop
      stop:
        command: down
        arguments: --volumes # Additional arg in down command so that volumes are removed
      skip:
        in-tests: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db-changelog.xml
  datasource:
    url: <>
    username: your_username
    password: your_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
