apiVersion: v1
kind: Service
metadata:
  labels:
    name: db
  name: db
spec:
  type: LoadBalancer #default ClusterIP
  ports:
    - name: db
      port: 27017
      targetPort: 27017
  selector:
    app: db
