apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - env:
            - name: SPRING_DATA_MONGODB_HOST
              value: db
            - name: SPRING_DATA_MONGODB_PORT
              value: '27017'
            - name: SPRING_DATA_MONGODB_DATABASE
              value: admin
            - name: SPRING_DATA_MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: SPRING_DATA_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
          image: dhananjay12/demo-app:3.0.0
          imagePullPolicy: Always
          name: demo-app
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
