version: "3.7"
services:
  demo-app:
    image: dhananjay12/demo-app:3.0.0
    environment:
      - SPRING_CONFIG_ADDITIONAL-LOCATION=/config/
    volumes:
      - ./:/config
    ports:
      - "8080:8080"