name: Main/master push/merge workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
      - release/*

jobs:
  push:
    uses: dhananjay12/reusable-workflows/.github/workflows/build.yml@main
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_PASSWORD }}