
name: Java CI with Maven

on:
  # To manually trigger
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  release:
    uses: dhananjay12/reusable-workflows/.github/workflows/release.yml@main
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_PASSWORD }}