name: Release Published

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  push:
    uses: dhananjay12/reusable-workflows/.github/workflows/release.yml@main
    secrets:
      REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      JFROG_URL: ${{ secrets.JFROG_URL }}
      JFROG_USERNAME: ${{ secrets.JFROG_USERNAME }}
      JFROG_TOKEN: ${{ secrets.JFROG_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_PASSWORD }}