
name: Release RC on master push

#on:
  # To manually trigger
#  workflow_dispatch:
#  push:
#    branches:
#      - master

jobs:
  release:
    uses: dhananjay12/reusable-workflows/.github/workflows/release.yml@main
    secrets:
      REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_PASSWORD }}