name: Release Published

on:
  release:
    types: [published]

jobs:
  check_pre_release:
    runs-on: ubuntu-latest
    steps:
      - name: Check parameters
        run: |
          echo "Release tag: ${{ github.event.release.tag_name }}"
          echo "Is a pre-release: ${{ github.event.release.prerelease }}"
      - name: Initialize Java and Maven
        uses: dhananjay12/reusable-workflows/.github/actions/init-maven@main
        with:
          java-version: 17
          distribution: adopt
      - name: Build with Maven
        run: mvn clean verify
      - name: Publish to GitHub Packages
        run: mvn  --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
