# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches:
      - master
      - release/*

jobs:

  deploy:
    if: ${{ github.ref == 'refs/heads/master'}}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Heroku
        env :
            HEROKU_REGISTRY_URL: registry.heroku.com
            HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
            HEROKU_APP_NAME: demo-app-github
        run : |
            docker login --username=_ --password $HEROKU_API_KEY $HEROKU_REGISTRY_URL
            heroku container:login
            heroku create
            docker pull dhananjay12/demo-app:latest
            docker tag dhananjay12/demo-app:latest registry.heroku.com/demo-app-github/web
            docker push registry.heroku.com/demo-app-github/web
            heroku container:run web --app $HEROKU_APP_NAME --port=8080
            heroku container:release web --app $HEROKU_APP_NAME
